### ISSUE TITLE
.7z roms just play the parent rom (reopened)

### ISSUE THREAD

**Issue by Ojousama** [MisterTea/MAMEHub#178]
.7z roms just play the parent rom. This is because MAMEHub launches games via filename and not by its MAME rom name. The auditor also misses a lot of roms when using 7z fullsets.

If you have a .7z fullset, and for example, start a game with the rom "bgareggahk", "bgaregga" will end up playing.

Command: ./csume64 "/home/johnmadden/sd/bgaregga.7z" -port 6805 -server -username JAM

What it should be: ./csume64 bgareggahk -port 6805 -server -username JAM

This works fine when using csume outside of MAMEHub.

**Comment by Prinygod** [comment]
currently full name isn't supported, so this is technically not a problem anymore
