### ISSUE TITLE
Access Violation in some games

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#252]
When I run ddrew.zip (D. D. Crew) or mt_srage.zip (Streets of Rage + Mega-Tech BIOS) they crash with an access violation.

Example: [PasteBin Link](http://pastebin.com/mqrnXH3k)

It works fine when I run without the -server argument (CSUME ddcrew) and crashes with it (CSUME ddcrew -server). 
Prinygod tested the same games and did not have this problem. So this is something on my end?

**Comment by MisterTea** [comment]
There's a discussion of the bug over there.  I'm closing this issue since this has nothing to do with mamehub (and we fixed it anyways)
