### ISSUE TITLE
Emulator runs Extremely Slow on some hardware (Atari 7800 & Arcade NBAJam)

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#289]
When I run an Atari 7800 game on MAMEHub it will run very slowly (~30%), but in MESS 0.149 and 0.154 they both run at 100%. The slowdown happens both with and without the -server argument.

I cannot seem find anything in particular in the logs.

**Comment by MisterTea** [comment]
We talked about this issue today, what was the consensus? Is it a 0.154 issue or a mamehub issue?  Also, please check the binary I just pushed and let me know if it's still there.

**Comment by christ776** [comment]
Hi ! I'm also having the same issue running MAMEHub on Mac OS X Yosemite.

**Comment by Prinygod** [comment]
the problem has been fixed with the new version closing

**Comment by Gitweazle** [comment]
Awesome. Thanks for fixing this one!
