### ISSUE TITLE
MESS Tree Bugs

### ISSUE THREAD

**Issue by TEOL85** [MisterTea/MAMEHub#292]
Ok, here goes.

Mess is currently working but to work around it not working we currently have to prat about and first make a folder for your system which is the first dogey thing as MAMEHub used to load the system from your normal roms folder automaticlly in previous versions and even then you are limited to only a few of the hashes working as the ones with the multiple setups when you name your loading folder to the main version of the XML in the tre of XML's for a multi type system those multiload XMLs won't scan in but the single ones like megadrive, nes, snes, tg16 do but if it's a same title game on different systems one version will load and the others won't but other than that the single formats work fine.

Secondly it won't scan anymore Good or No-Intro sets with the names like they are anymore. Instead you have to rename them to stuff like the zip being named the short game name listed in the hash file and then the file inside has to be names to the long name written exactly like it is in the hash.

Thridly for some games you can't use a No-Intro/Good/NonGood/TOSEC veriation at all as they are listed as 2 file splits which you can only get from Jammaplay or some torrent site I don't like using with too many downloading and uploading slowing the internet speed down after you finished your download rules because they force you to leave upload on for the rest of the day.

Yeah, basiclly to work around MESS working now you have to prat about now making folders that match the hash name and make the games match the zip and long name what is listed inside the hash and for 2 file split games you have to go Jammaplay when single file versions got detected in the past and in the past your games were detected by CRC matchup rather than filenames and then you have the annoying thing where if you have 2 ports with the same name like Parasol Stars on the TG-16 and Parasol Stars on the N.E.S./NES/Famicom the only NES one that loads up is the Prototype and the TG-16 ones fine as well but the final doesn't even get detected.

Hope these MESS discriptions help as MESS is a chore and a MESS getting working in MAMEHub currently in the new version.

Maybe putting the No-Intro/TOSEC/NonGood/Good CRC codes from the dats in replacing the default info in the hash files would fix part of it to load the proper 1 file versions up at least who knows peferiblely No-Intro for normal games, Good for homebrew and trannys and Non-Good and Tosec for the pirate, multicart and missing homebrew and tranny entries and then it would make the full collection being able to run if thats how the MESS roms hash system works to make a superior romset exclusive to MAMEHub with every game CRC ever dumped to run on it or at least just the No-Intro set the most used one now working well we at least must have a set where you don't need a folder and naing system to load the game?

Anyway to get it sorted so it runs like MAMEHub classic autoscaning with any filename and foldernames you like is all I want really a massive custom MAMEHub romset fopr these is just extra baggage really.

**Comment by MisterTea** [comment]
MESS broke manually specifying the files and also required per-system directories as of 0.154, so we can't do anything about that.
