### ISSUE TITLE
Sudden Input Delay

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#293]
Occasionally when playing with other people, somebody starts to lag and as a result the game suddenly has increased input delay (response time). However, after the lag had cleared the input delay will stay and not decrease anymore, making the game unplayable.

Here is a log of a game where this happened:
Player 1 (no lag): [Link 1](http://pastebin.com/8TSUHV93) - *(note: MISSING INPUT DATA FOR PLAYER 2 AT 358)*
Player 2 (no lag): *(he left before I could ask for log)*
Player 3 (lagged): [Link 2](http://pastebin.com/431qj0bn) - *(note: GOT PARTIAL RESYNC)*

Even after Player 3 logged off the input delay would remain high.

**Comment by MisterTea** [comment]
This was a bug with the way syncs were batched that should be fixed now.  Please re-open if it's still a problem.
