### ISSUE TITLE
Official MESS NES rom (btoadsddu.zip) freezes.

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#299]
Battletoads & Double Dragon for the NES hangs when the stage boss ABOBO smashes through the door. (ABOBO wins!).

This does not happen on the **.nes** version ROM when you start it with full path method.

**Comment by MisterTea** [comment]
This sounds like a bug in MESS.  Did you file it on their bug tracker?

**Comment by Gitweazle** [comment]
Bug has been reported to MAME Testers. [pic](http://postimg.org/image/3p0p30oqf/)
