### ISSUE TITLE
Mamehub 3.1 has really bad input delay

### ISSUE THREAD

**Issue by 995phil** [MisterTea/MAMEHub#303]
Even when set to 0 natively, the input delay is terrible.  As a fighting game fan, it's simply cannot be used for fighters, especially when some combos require to-the-frame inputs that are impossible with such input delay.

Mamehub is amazing for Mortal Kombat since we don't have anything that uses netcode this good, but we are forced to use Mamehub 3.0 because of the input delay.  Hopefully this can be fixed.

Thanks, -995Phil

**Comment by MisterTea** [comment]
I pushed a new version of the emulator that has experimental support for 0-latency netplay.  To enable it, add this to your ini file:

    rollback       1


Closing this issue.  Re-open or create a new issue if there are problems with rollback.

**Comment by WhompMaste** [comment]
I’m not exactly sure where to add this in the ini file but I’ll look for it tonight when I get home.

**Comment by MisterTea** [comment]
@WhompMaste you can add it anywhere as long as it's on its own line

**Comment by WhompMaste** [comment]
One last question.  Do we both need to add this to the ini file or just the person hosting the game?

Date: Thu, 8 Jan 2015 09:11:17 -0800

**Comment by MisterTea** [comment]
Currently both people need to add it.

**Comment by WhompMaste** [comment]
Ok, cool.  Thanks!

Date: Thu, 8 Jan 2015 10:43:07 -0800

**Comment by WhompMaste** [comment]
I have tried multiple times with my partner to get this working and mamehub simply will not connect.  Is it possible to email a picture of exactly how and where you have it added in your .ini file?  Him and I both have it added on it's own line in the same location as each other but now we can't connect.
Thanks! 

Date: Thu, 8 Jan 2015 09:11:17 -0800

**Comment by MisterTea** [comment]
So just to be clear: When you have rollback set, you can't connect, but when you don't set it you can connect fine?  Please send the logs of your failed connect (both you and your partner's) and I can investigate.

**Comment by WhompMaste** [comment]
I’m sure someone else has tested this out and it worked, right?  So I would like to make sure we both have it added in correctly first compared to yours.  There is a built in tool on Windows (if you use Windows 7) called Snipping tool.  You just click on it and drag around something and it will make a picture of it.  Can you either do this and make a pic of how yours looks and send it to me or maybe send me a copy of your .ini file JUST to make sure I have it setup right?

Thanks!

**Comment by Prinygod** [comment]
roll back and netcode had gotten some fixes as well as a performance fix, please verify if there is still a problem

**Comment by WhompMaste** [comment]
Well, I never could get roll back to even work in my txt file.  I think (been a while back) we could never connect so we just remove it all together.   It's so weird but sometimes we can play a whole game which may be close to a hour (1 game) and never see this delay bug and then it will happen right away in the next game. 

Date: Thu, 9 Apr 2015 13:36:48 -0700

**Comment by MisterTea** [comment]
@WhompMaste Rollback was buggy until NOW.  Try it again, it's fucking amazing.

Also the delay bug is fixed.  Was a timestamp issue.

**Comment by WhompMaste** [comment]
Awesome!  We are going to try it tonight!  Thanks!

Date: Thu, 9 Apr 2015 14:06:16 -0700
