### ISSUE TITLE
Getting lots of: package com.mamehub.thrift does not exist

### ISSUE THREAD

**Issue by audiodude** [MisterTea/MAMEHub#308]
When trying to build the client with this command:

$ mvn package

from this folder:

MAMEHub/Sources/Client

I get a maven error like so:

[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:50.349s
[INFO] Finished at: Wed Dec 10 22:15:29 PST 2014
[INFO] Final Memory: 15M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project MAMEHubClient: Compilation failure: Compilation failure:
[ERROR] /Users/tmoney/Desktop/games/MAMEHub/Sources/Client/src/main/java/com/mamehub/client/utility/OSValidator.java:[3,25] error: package com.mamehub.thrift does not exist
[ERROR] /Users/tmoney/Desktop/games/MAMEHub/Sources/Client/src/main/java/com/mamehub/client/utility/OSValidator.java:[53,15] error: cannot find symbol
[ERROR] class OSValidator
[ERROR] /Users/tmoney/Desktop/games/MAMEHub/Sources/Client/src/main/java/com/mamehub/client/net/RpcEngine.java:[29,22] error: package com.mamehub.rpc does not exist
[ERROR] /Users/tmoney/Desktop/games/MAMEHub/Sources/Client/src/main/java/com/mamehub/client/net/RpcEngine.java:[30,22] error: package com.mamehub.rpc does not exist
[ERROR] /Users/tmoney/Desktop/games/MAMEHub/Sources/Client/src/main/java/com/mamehub/client/net/RpcEngine.java:[31,25] error: package com.mamehub.thrift does not exist
...

And it kind of just goes on like that for a while.

The source I'm using is taken from doing "Download zip" from the github front page, so I think it's the HEAD version.

Thanks!

**Comment by MisterTea** [comment]
I added info on this to the README.
