### ISSUE TITLE
Can no longer connect to other peers

### ISSUE THREAD

**Issue by Jaku2k** [MisterTea/MAMEHub#312]
I am getting kicked out of other peoples game instantaneously, with or without the rollback. 
host (win):http://pastebin.com/jWNGF1LE
client (lnx): http://pastebin.com/6q0YByaF

host (lnx):http://pastebin.com/z2wRpKym
client (lnx):http://pastebin.com/vhLcrBpR

**Comment by Jaku2k** [comment]
same with mac
server (lnx):http://pastebin.com/vbF7UxVx
client (mac):http://pastebin.com/SKkQj16s

**Comment by MisterTea** [comment]
I believe this is because I forgot to deploy the fixed binary on mac.  I'm building a new mac binary that should be uploaded in 2 hours.  Please let me know if this is still an issue by re-opening.  Thanks.

**Comment by Jaku2k** [comment]
Im sorry. 
I didnt know how to re-open. Supposedly there is a button somewhere?
