### ISSUE TITLE
Server crashed...

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#316]
With the following error:

*Disk quota exceeded.* [LOG](http://pastebin.com/ANdUD8bY)

**Comment by MHSimetra** [comment]
So it wasn't just me! :P I feel less bad now.

**Comment by Gitweazle** [comment]
Server is up, name database has been reset. Re-registered.

**Comment by MisterTea** [comment]
See this blog post for details: http://mamehub.tumblr.com/post/107446863667/server-database-wipe-part-2
