### ISSUE TITLE
Latest CSUME (01-10-2015 15:44) Offline Mode Error

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#318]
The latest version of CSUME does not work in offline mode anymore (without -server argument, thanks Jaku); On Windows I get a Access Violation. Linux also has similar problems (segmentation fault).

Exception at EIP=029321D7 (test_then_block+0x00c7): ACCESS VIOLATION
While attempting to read memory at 000000A4

EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000000
ESI=00000000 EDI=0022FE50 EBP=0022B0C8 ESP=0022AF20

Stack crawl:
  0022B0C8: 029321D7 (test_then_block+0x00c7)
  0022B588: 02933537 (LoadFunction+0x02f7)
  0022B758: 0296BADF (sqlite3_backup_init+0x0034)
  0022F708: 0297DCFB (sqlite3VdbeExec+0x8348)
  0022F978: 02A29FDF (device_t* device_creator<i8021_device>(machine_config const&, char const*, device_t*, unsigned int)+0x00cf)
  0022FEB8: 019E7775 (adsp2101_device::adsp2101_device(machine_config const&, char const*, device_t*, unsigned int)+0x0015)
  003F2890: 02ED3310 (dc_cons_state::~dc_cons_state()+0x0110)
  003F4710: 003F27F0 (+0x3f27f0)
  00730063: 006D0075 (gaelco2_state::gaelco2_palette_w(address_space&, unsigned int, unsigned short, unsigned short)+0x0135)
  8502E0C1: 244489C0 (register_frame_ctor+0x1fc08150)

**Comment by MisterTea** [comment]
Is this true for all roms?

**Comment by Jaku2k** [comment]
yes, the emulator alone wont run.
