### ISSUE TITLE
Problems compiling CSUME

### ISSUE THREAD

**Issue by ghost** [MisterTea/MAMEHub#331]
Hi there,

I've been compiling regular MAME for a little while now and know to a small extent what is required.

But, for the life of me, I cannot seem to successfully compile CSUME without getting some sort of error. The error messages involved vary depending on what version of MinGW I use and the command line I use. It appears (and I could be wrong) the instructions on the main page aren't up to date, so I was wondering if someone could post some clear, and I emphasize clear  :)  instructions on what to do. i.e the correct software I need (including links to them) and the command line I need to use.

For various reasons it's essential that I compile my own CSUME.

My latest attempt was to use the latest "buildtools" found on the mamedev forum and to use the makeMameWin64.bat file that was included with the CSUME source. I edited the MinGW paths of course. Compiling on Windows 8.1 x64. Using the latest CSUME Source.

But after some time I got these error messages:

process_begin: CreateProcess(NULL, python src/emu/cpu/h8/h8make.py src/emu/cpu/h
8/h8.lst o obj/cswindows64d/emu/cpu/h8/h8.inc, ...) failed.
make (e=2): The system cannot find the file specified.
src/emu/cpu/cpu.mak:650: recipe for target 'obj/cswindows64d/emu/cpu/h8/h8.inc'
failed
make: *** [obj/cswindows64d/emu/cpu/h8/h8.inc] Error 2
make: *** Waiting for unfinished jobs....

As I mentioned the errors vary depending on version of MinGW and command line I use.

My apologies if this has been answered already but couldn't find anything definitive and easy to understand in order to answer my question.

Thank you very much.

**Comment by MisterTea** [comment]
You can see the command I use to build MAME, it's in the repo:

```
Emulator git:master ❯ cat makeMameWin32.bat                                                     ✹ ✭
set PATH=c:\mingw-mame\mingw64-w32\bin;c:\MinGW\msys\1.0\bin;%PATH%
make -j8 NOWERROR=1 PTR64=0 TARGET=ume
```

From your error, it looks like you are missing python.
