### ISSUE TITLE
Linux mint missing library?

### ISSUE THREAD

**Issue by Prinygod** [MisterTea/MAMEHub#332]
user on linux mint could not run, turns out to have a missing library, had ran the shell script.

"/csume64: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory"

Perhaps it should be added to the library script

**Comment by Jaku2k** [comment]
yeah, DG forgot to update it, the library script is still using v1.2.

**Comment by Prinygod** [comment]
added the missing library just needs to be pushed
