### ISSUE TITLE
problems logging in ubuntu and linux mint

### ISSUE THREAD

**Issue by Prinygod** [MisterTea/MAMEHub#335]
some times gets error after trying to log on in linux. I am able to get to the log in, and put in my password, but after loging in i get the "could not instantiate class error"

https://gist.github.com/Prinygod/c0c8b1a198de45918b21

**Comment by hirkyflobble** [comment]
Confirmed. That's why I haven't been on while in Linux in quite some time. Oddly enough though, if launched with the MAMEHub.sh, you can log right in. This issue seems to only happen with MAMEHubClient.jar for me. But I want to use my custom hash files.

**Comment by MisterTea** [comment]
Yeah I've had that problem. It's some issue with the database MAMEHub uses
on Linux. I'll see if there is any improvement.

**Comment by BadDude** [comment]
I get same error on Ubuntu (15.04).

**Comment by BadDude** [comment]
If someone else has the same issue... I fixed it by unsetting the environmental variable JAVA_TOOL_OPTIONS, which in Ubuntu 15.04 is set to -javaagent:/usr/share/java/jayatanaag.jar (I don't know if it is also the case for previous releases)

**Comment by MisterTea** [comment]
Wow, that is really the problem? Weird. Anyway, I updated map db to the
latest version and haven't gotten the problem in Linux so I believe this
issue is closed.
