### ISSUE TITLE
MAMEHub 3.2 (UME 0.160) update downloads 64-bit csume.exe on 32-bit Windows?

### ISSUE THREAD

**Issue by al-Afdal** [MisterTea/MAMEHub#340]
At least, I believe that's what the problem is.  I am running Windows XP.  Trying to make games in MAMEHub states that an exception has occurred and then boots me from the server, while trying to join games results in no csume client loading.  In either case no game log gets generated.  Trying to run csume.exe directly from the MAMEHubRepo\Binaries\dist directory results in the error "csume.exe is not a valid Win32 application".

**Comment by MisterTea** [comment]
Mame/Mess 160 doesn't support cross compiling from 64 bit to 32 bit and all of my machines are 64 bit so I have no way to build a 32 bit binary at the moment.

**Comment by al-Afdal** [comment]
Is this something someone else could take care of easily or is it rather complicated?  How have you been compiling the 32-bit versions previously?

**Comment by MisterTea** [comment]
Previous my 64-bit machine could compile the 32-bit version.  I can spin up a 32-bit VM but it will take time.  It's probably faster to get a 64-bit OS

**Comment by al-Afdal** [comment]
I guess I'll wait patiently then.  Thanks!  I've waited years to finally netplay Raiden DX so a little longer won't hurt :D

**Comment by MisterTea** [comment]
You could also get a 64-bit machine for like $200 :-)

**Comment by Prinygod** [comment]
What processor do you have? A lot of people don't realise they have a 64 bit processed and install a 32 bit one because they didn't know

**Comment by al-Afdal** [comment]
I sure do miss using MAMEHub :'(

**Comment by al-Afdal** [comment]
I sure miss MAMeHub I:<

**Comment by MisterTea** [comment]
I still think you guys are crazy for not upgrading your rig to 64-bit, but I went ahead and built a 32-bit VM and 32-bit binaries so it works now.
