### ISSUE TITLE
Issue with controls while playing with intel graphics.need to change default keyboard keys

### ISSUE THREAD

**Issue by babarlhr** [MisterTea/MAMEHub#342]
i have not found any option to change controls i want to change keyboard control. because when using with intel graphics ALT+CTRL+arrows keys use to change orientation of screen to 180 degree 90 degrees respectively so when during playing games  we press these keys it passed to the intel and screen orientation is change and after that game struck for few seconds and game screen changes to 180 degrees or 90 degree

**Comment by MisterTea** [comment]
Press tab while in a game to change controls
