### ISSUE TITLE
Can't log in; Missing eu.png

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#343]
I was unable to log in because of missing resources. Updating with MAMEHub.bat did not remedy it.

en.png
eu.png

I fixed it by changing some file names (english.png, europeanunion.png) in MAMEHubClient.jar

**Comment by MisterTea** [comment]
Hey, is this still an issue?

**Comment by Gitweazle** [comment]
This just happened out of the blue again. All names disappeared in the lobby, I tried to reconnect to solve the issue and got the missing resource error.

Fixed it again by changing the same files to eu.png & en.png

**Comment by MisterTea** [comment]
Can you make a pull request with the missing files?
