### ISSUE TITLE
Error when updating during install....

### ISSUE THREAD

**Issue by matthewr88** [MisterTea/MAMEHub#344]
Hi,

I'm getting the below error when installing...

![image](https://cloud.githubusercontent.com/assets/12818259/8065613/6c1bd230-0eda-11e5-94e0-27cc9973c720.png)

Any help?

Thanks

Matt

**Comment by MisterTea** [comment]
If you get MAMEHub 4.0, this problem should disappear. Please let me k ow
if it's fixed, thanks

**Comment by Prinygod** [comment]
please reopen if still a problem
