### ISSUE TITLE
Can't log in, password recovery not working.

### ISSUE THREAD

**Issue by Rong-Yao** [MisterTea/MAMEHub#351]
Not sure if this is a server issue but i've made an account
RongYao
everything worked fine, played several times, then month later i tried to login, don't remember my password, so i've attempted to go for password recovery, still it says that email is not found.

Is account deleted or recovery fails?

**Comment by Gitweazle** [comment]
Try re-registering the name again, the database has been reset a few times in the last months.

**Comment by Rong-Yao** [comment]
It is just saying that Username is already registered. So great, someone probably took over my username and i was not notified.

**Comment by Rong-Yao** [comment]
Also i did register it after the wipe. So, not sure why i cannot recover.

**Comment by Prinygod** [comment]
there is no verification of email, if you put the email in wrong, it wont be sent to the right place. Be sure to check your spam folder. There is not much we could do other than erase your username
