### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by Jaku2k** [MisterTea/MAMEHub#360]
get a NotAuthorizedException error when I click the login button
http://pastebin.com/sFAs8Rf0

**Comment by Gitweazle** [comment]
Same here, it is most likely the scheduled downtime. [\[Link\]](http://mamehub.tumblr.com/post/131312206022/hey-all-mamehub-will-be-under-some-server)

**Comment by MisterTea** [comment]
What happens if you make a new account?

**Comment by MisterTea** [comment]
I looked at the error message: looks like you are running an outdated
client. It should update automatically.

**Comment by Gitweazle** [comment]
Hmm, at first I thought it was because I start with MAMEHubClient.exe, but I tried running MAMEHub.bat just now and I get this:

[Error Log](http://pastebin.com/ZsfjVBfx)

I will download and reinstall v4.0 and see if that runs.

**Comment by MisterTea** [comment]
When you reinstall 4.0, make sure you do it in an empty directory.

**Comment by Gitweazle** [comment]
Ok that worked. Only error I got at startup was "Could not find UpdateFirewall.bat" even though it's clearly there.

**Comment by MisterTea** [comment]
Weird. You can run updatefirewall manually. Just make sure you run it as
admin.

**Comment by Gitweazle** [comment]
By the way, it still says 3.2 on log in screen and in the Lobby :toilet:

**Comment by Jaku2k** [comment]
Installing mamehub 4.0 worked but dont have permission to execute MAMEHub.sh and installLinuxDeps.sh script.

**Comment by MisterTea** [comment]
Oh, you can fix that with chmod. I'll make a new zip with the right
permissions later today.

**Comment by Jaku2k** [comment]
Also I got a bunch of html documents in almost every folders.

**Comment by MisterTea** [comment]
The html documents is a known issue because of how we mirror the files.

**Comment by MisterTea** [comment]
Mamehub client is going away
