### ISSUE TITLE
Problem with large hash files!

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#368]
I am in the process of adding non-MESS ROMs to the XML hash files. I have started doing NES, which is one of the largest (~22MB). I am running into several problems, and I could use some help testing.

I can't find any errors in the XML code, but CSUME acts very erratically. Some games will boot, others will make CSUME hang and run in the background with 99% CPU, no window. Official MESS roms sometimes report 'file not found'.

This happens regardless if I run through MAMEHub or command line.

I tried the same hash on MAME 0.169b and it runs without a hitch.

If somebody wishes to lend me a hand, here is the file:
[Download NES HASH](https://www.sendspace.com/file/2vacb4)

**Comment by Gitweazle** [comment]
Still trying to figure out why it hangs...

Is the auditor able to handle duplicate entries? For example: 2 ROMs with the same name but different SHA-1, or 2 ROMs with different names but the same SHA-1?

**Comment by MisterTea** [comment]
Mamehub client is deprecated
