### ISSUE TITLE
Server is down.

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#374]
Server crashed yesterday and hasn't been up since.

**Comment by Gitweazle** [comment]
It's back up. Closing.

**Comment by MisterTea** [comment]
Thanks for letting me know it was down and now it's back up.

**Comment by Gitweazle** [comment]
I gave you a thumbs up and a party hat!

**Comment by Gitweazle** [comment]
Server is very laggy at the moment and keeps crashing.

**Comment by MisterTea** [comment]
The crashes are probably timeouts.  It looks like there's a networking issue with the mamehub server's hosting provider.  I'll post again when I know more.

**Comment by Gitweazle** [comment]
It seems to have cleared. Closing again!

**Comment by Gitweazle** [comment]
The server seems to be down.

**Comment by MisterTea** [comment]
Restarted it, thanks.

**Comment by Gitweazle** [comment]
Thanks a bunch! Closing.
