### ISSUE TITLE
Csume for windows x86 ?

### ISSUE THREAD

**Issue by MrRyuu** [MisterTea/MAMEHub#388]
Hello!

Pls, I need to know where can I download "csume.exe" for **Windows x86**. The Mamehub 4.0 only bring "csume64.exe" (released for x64 systems). This isn't working for me.

I need revert to the previous version 0.154.

Thank you in advance!

**Comment by Gitweazle** [comment]
Delete csume64.exe in the dist folder, start MAMEHub client and select **File -> Update Emulator**

**Comment by MisterTea** [comment]
32 but won't be supported anymore. 64 bit has been around for over a decade.
