### ISSUE TITLE
Machine Learning & Latency Prediction

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#392]
Been a while since I posted here. This is not really an issue, but more of a random thought I had a while back. Since you are quite familiar with AI and machine learning, @MisterTea , I was wondering what your insight was in the application of AI to internet traffic, such as the latency prediction methods used for games.  The AI could even be fine-tuned to adapt to each individual's online behaviour.

Is this feasible or even useful in the near future?

**Comment by MisterTea** [comment]
Mamehub already does this. It uses statistics (loosely ML) to decide the input delay so the game doesn't stutter.
