### ISSUE TITLE
MAMEHUB Client Can't find Taito GNET GAMEs

### ISSUE THREAD

**Issue by beeion** [MisterTea/MAMEHub#394]
I have ray crisis CHD and psyvariar CHD with taito g net zip.
but the client never find them no matter what happen.
(these game can run in csume64 without client)

i think there is something wrong in audit process.

maybe because the taito g net game don't use zip file in each game unlike other game (street fighter 3, killer instinct)?

is there someone to fix this?

**Comment by Gitweazle** [comment]
I think it may have to do with the CHD version, similar to described in issue #146 

You could check the SHA-1 with chdman.exe included in vanilla MAME and compare it with the hash value found in .../MAMEHubRepo/Binaries/hash/mameROMs.xml.gz

**Comment by beeion** [comment]
vanilla mame? i didn't hear this one is exist.

so what you saying is
TO detect only chd using game (no need zip file to run) i need to change hash value in mameROMs.xml.gz?

but unfortunately i can't found mame. vanilla mame.

i want you give me some more detail.

**Comment by Gitweazle** [comment]
Sorry, with vanilla MAME I meant the original MAME http://mamedev.org/

I will check if I can get the game to run.

**Comment by beeion** [comment]
So it means
even if update chd file to v5 mamehub can't locate raycris.chd or psyvariar.chd?

Kinda strange but shame.

**Comment by beeion** [comment]
Which means
even if update raycris.chd or psyvariar.chd version to 5 mamehub can't find it?

This is not good.

**Comment by Gitweazle** [comment]
You could still play using CSUME64.exe and command line arguments; online even. The wiki page shows how. You just won't have a lobby.

**Comment by beeion** [comment]
inputting
[documents\MAMEHub\MAMEHubRepo\Binaries\dist\csume64.exe]
can access to mame (though not playable).
using cmd somewhat complicated.

but with these what you said it still hard to understand.
i need more example.

i can't understand GAP in the [csume64 psyvaria]. AND [-server-] what is that mean? it has to add "- -"?

**Comment by Gitweazle** [comment]
From my example, these are all commands. -server indicates you act as the host. -client is the person that will connect to the host. Only the client has to input your IP (and port).

So to be clear, it is not -server- or - server. And "" are not included, it is a quotation mark.

**Comment by beeion** [comment]
sorry. still hard to understand with these because i don't know much about cmd.
but i manage to access to mameclient with cmd somehow

BY INPUT
documents\mamehub\mamehubrepo\binaries\dist\csume64 psyvaria -server -port 6805 -username bee.
(too complicated for me).

but there is problem. with these command you instructed I CAN'T LOAD THE GAME even if using another game like gunforce.
I ALSO MOVING GAME ROM TO dist folder and TRY AGAIN BUT FAILED. NOTHING WORK.

is there something i missing?

**Comment by Gitweazle** [comment]
I made a batch file a long while ago, in the event the server ever goes down. It is pretty straightforward, but only in English. Press 1 to start a new session, then go through each menu item.

[CSU_Menu](https://www.sendspace.com/file/pxzhdr)

Unpack it to your main MAMEHub folder, the same place where MAMEHub.bat is located.

**Comment by beeion** [comment]
here is some question. i used your file. set the game and started with window 10 64bit processor.
changed play more from offline to server but it's not working (dsmbl.zip or gunforce,zip was used.).

if i want to use psyvaria.chd. how to i write this? just enter psyvaria.chd won't let pass to the "what is your bit? 32 or 64 bit?"

**Comment by Gitweazle** [comment]
Enter psyvaria.chd
So it does not ask if you wish to play in full screen after entering 64? That is a very simple line of code and I would not know why that would not work and the other more complex code works fine.

Can you save the settings (option 8) and send CSU_Menu.sav to me? It is a simple text file, which shows me the settings you entered.

I do not have Windows 10, so I cannot test it. If this does not work, I fear I cannot help you any further.

**Comment by beeion** [comment]
SERVER
-server -port 6805
-hostname 175.114.222.50
-port 6805
-selfport 6805
-username "beeion"
ARCADE

psyvaria.chd
c:\documents\MAMEHub\MAMEHubRepo\Binaaries\roms
-rp "c:\documents\MAMEHub\MAMEHubRepo\Binaaries\roms"

[CSU_Menu.txt](https://github.com/MisterTea/MAMEHub/files/2366939/CSU_Menu.txt)

sorry. i have to change ".sav" to ".txt" to send this file.

**Comment by Gitweazle** [comment]
Thanks. Don't post your IP :)

**Comment by beeion** [comment]
sending another sav file
[CSU_Menu.txt](https://github.com/MisterTea/MAMEHub/files/2367236/CSU_Menu.txt)

**Comment by beeion** [comment]
okay. it worked. only tested psyvaria.chd. but it worked. can playable with client.
there some video skip due to the some slow. usually show base delay is 210.
but it's working on CSU-Menu not mame so i will leave this until it's working on mamehubclient.

by the way there is some question about CSU_MENU.
when i start the game i can see choose 32bit or 64bit.
which means even if the operation bit is different but still playable in online?

**Comment by MisterTea** [comment]
Mamehub client will die and people will use Discord to arrange games, so closing this.
