### ISSUE TITLE
Problem about reset the game (CAN'T RUN PC ENGINE CD GAMES)

### ISSUE THREAD

**Issue by beeion** [MisterTea/MAMEHub#398]
IN CSMAME IF RESET THE SYSTEM THE GAME WILL BE RESET AND PLAYABLE.
HOWEVER IN CLIENT IF RESET THE SYSTEM THE MAME WILL UNABLE TO USE. 

like this i was able to load pc engine game by using these.

start with [cd] super cd-rom system (Japan) (v3.0).pce first.
then load hellfire s - the another story (cd)(jpn).chd IN MAME FILE MANAGER OPTION (changed hash sha1 but nothing happen)
then load [cd] super cd-rom system (Japan) (v3.0).pce IN MAME FILE MANAGER OPTION (CAUSE RESET THE SYSTEM) 
problem is if do like that the mame won't working. 

is there someone to fix?

**Comment by MisterTea** [comment]
Reset is a bad idea. The networking code assumes that we are always moving forward in time, and resetting breaks that assumption. Is there any way to play that game without resetting?

**Comment by beeion** [comment]
I like to. but everytime i load system card i have to put chd first. But if do that it show "just moment" then nothing working.

And then select cart it will automatically reset.

I wonder how to solve this problem without reset.

**Comment by beeion** [comment]
Solved. by doing these

1. PUT SCDSYS.ZIP AND hellfire s - the another story (cd)(jpn).chd into PCE FOLDER

2. Create mklink by using command prompt in roms folder (then input "mklink /d pcecd pce" in command prompt.).

3. Move all Pcecd.xml text into Pce.xml in hash folder

4. input "cart scdsys" in pce.ini (it's in ini folder)

if this is not window maybe solving the problem will be different.
it's not working on new mamehub but i will close this issue.
