### ISSUE TITLE
Ding or Email when your favorite game is hosted or when someone joins your hosted game

### ISSUE THREAD

**Issue by bazzinotti** [MisterTea/MAMEHub#54]
Often enough when you go on Mamehub, there's nobody interested in your favorite game. If you host a game, there's no sound popups when someone joins or anything.

Not only am I asking for sounds when someone joins my game.. What would be awesome if I'm idling in Mamehub waiting for someone. I start doing something else on the computer, if MAMEHUB said "hey someone is hosting your favorite game!!" it would be cool if i could set what games to be notified when those games are being hosted.

Even cooler would be having the options to be emailed when my favorite games are being hosted on mamehub. If im not doing anything I could go ahead and join in!!

**Comment by MisterTea** [comment]
Arranging games is better done through reddit/facebook
